### PR TITLE
Use sub_property instead of sub-property.

### PR DESCRIPTION
**Pull request by chasingmaxwell**
This is for consistency with the restful module. https://github.com/RESTful-Drupal/restful/blob/7.x-1.x/plugins/restful/RestfulEntityBase.php#L29

### CODE REVIEW

**Comment by e0ipso** [comment]
Tests seem to be broken.

**Comment by chasingmaxwell** [comment]
Looks like there's an issue with a patch that's being applied to the entity module in the build.

https://travis-ci.org/RESTful-Drupal/restful_search_api/builds/57752754

```
patch -p1 /home/travis/build/restful_search_api/drupal/sites/all/modules/entity/includes/entity.wrapper.inc < 2264079-entity-wrapper-access-single-entity-reference-2.patch
patching file /home/travis/build/restful_search_api/drupal/sites/all/modules/entity/includes/entity.wrapper.inc
Reversed (or previously applied) patch detected!  Assume -R? [n]
```

**Comment by e0ipso** [comment]
Please update to the latest 7.x-1.x changes to allow tests to run.

**Comment by e0ipso** [comment]
This has been merged as well. I apologize again for the delay.

Thanks for the contribution!

3db287eb1d4200b5cd450e346a555febe8880af6

**Pull request closed without merging**
